#define IDENTIFIER 100
#define CONSTANT 1
#define IF 2
#define ELSE 3
#define WHILE 4
#define RETURN 5
#define VOID 6
#define INT 7
#define CHAR 8
#define READ 9
#define WRITE 10
#define PUBLIC 11
#define STATIC 12
#define SimonaHalep 13
#define PLUS 14
#define MINUS 15
#define MULTIPLY 16
#define DIVIDE 17
#define MODULO 18
#define SIMPLE_EQUAL 19
#define DOUBLE_EQUAL 20
#define DIFFERENT 21
#define NEGATION 22
#define LESS 23
#define LESS_OR_EQUAL 24
#define GREATER_OR_EQUAL 25
#define GREATER 26
#define LEFT_SQUARE 27
#define RIGHT_SQUARE 28
#define LEFT_BRACKET 29
#define RIGHT_BRACKET 30
#define LEFT_ROUND 31
#define RIGHT_ROUND 32
#define COMA 33
#define SEMI_COLON 34
#define STOP 35
